# Generated by Django 5.1.1 on 2024-09-15 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_person_remove_quote_author_remove_quote_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quotes.person'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quote',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quotes.person'),
            preserve_default=False,
        ),
    ]
