# Generated by Django 5.1.1 on 2024-09-15 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_alter_image_person_alter_quote_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quotes.person'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quotes.person'),
        ),
    ]
